# Jekyll configuration

# Site settings
title: 2016 Annual Report
email: info@loudounchamber.org
description: 2016 Annual Report
baseurl: ''
url: "http://annualreport.loudounchamber.org"
cdnurl: "https://d2o0out0f0eahq.cloudfront.net"

# Data
company:
  name: Loudoun Chamber of Commerce
  website: http://www.loudounchamber.org


# Build settings
markdown: kramdown
include: ['_pages']
exclude: ['package.json', 'node_modules', 'gulpfile.js']

# Posts
permalink: /articles/:year/:month/:title/

